PHP_ARG_ENABLE(zend, whether to enable zend, [ --enable-zend   Enable Zend])

if test "$PHP_ZEND" = "yes"; then

	

	if ! test "x" = "x"; then
		PHP_EVAL_LIBLINE(, ZEND_SHARED_LIBADD)
	fi

	AC_DEFINE(HAVE_ZEND, 1, [Whether you have Zend])
	zend_sources="zend_.c kernel/main.c kernel/memory.c kernel/exception.c kernel/hash.c kernel/debug.c kernel/backtrace.c kernel/object.c kernel/array.c kernel/extended/array.c kernel/string.c kernel/fcall.c kernel/require.c kernel/file.c kernel/operators.c kernel/concat.c kernel/variables.c kernel/filter.c kernel/iterator.c kernel/exit.c zend/authentication/adapter/dbtable/exception/exceptioninterface.zep.c
	zend/authentication/adapter/dbtable/exception/invalidargumentexception.zep.c
	zend/authentication/adapter/dbtable/exception/runtimeexception.zep.c
	zend/authentication/adapter/exception/exceptioninterface.zep.c
	zend/authentication/adapter/exception/invalidargumentexception.zep.c
	zend/authentication/adapter/exception/runtimeexception.zep.c
	zend/authentication/adapter/exception/unexpectedvalueexception.zep.c
	zend/authentication/adapter/http/exception/exceptioninterface.zep.c
	zend/authentication/adapter/http/exception/invalidargumentexception.zep.c
	zend/authentication/adapter/http/exception/runtimeexception.zep.c
	zend/authentication/exception/exceptioninterface.zep.c
	zend/authentication/exception/invalidargumentexception.zep.c
	zend/authentication/exception/runtimeexception.zep.c
	zend/authentication/exception/unexpectedvalueexception.zep.c
	zend/barcode/exception/exceptioninterface.zep.c
	zend/barcode/exception/invalidargumentexception.zep.c
	zend/barcode/exception/outofrangeexception.zep.c
	zend/barcode/exception/renderercreationexception.zep.c
	zend/barcode/exception/runtimeexception.zep.c
	zend/barcode/exception/unexpectedvalueexception.zep.c
	zend/barcode/object/exception/barcodevalidationexception.zep.c
	zend/barcode/object/exception/exceptioninterface.zep.c
	zend/barcode/object/exception/extensionnotloadedexception.zep.c
	zend/barcode/object/exception/invalidargumentexception.zep.c
	zend/barcode/object/exception/outofrangeexception.zep.c
	zend/barcode/object/exception/runtimeexception.zep.c
	zend/barcode/renderer/exception/exceptioninterface.zep.c
	zend/barcode/renderer/exception/invalidargumentexception.zep.c
	zend/barcode/renderer/exception/outofrangeexception.zep.c
	zend/barcode/renderer/exception/runtimeexception.zep.c
	zend/barcode/renderer/exception/unexpectedvalueexception.zep.c
	zend/cache/exception/badmethodcallexception.zep.c
	zend/cache/exception/exceptioninterface.zep.c
	zend/cache/exception/extensionnotloadedexception.zep.c
	zend/cache/exception/invalidargumentexception.zep.c
	zend/cache/exception/logicexception.zep.c
	zend/cache/exception/missingdependencyexception.zep.c
	zend/cache/exception/missingkeyexception.zep.c
	zend/cache/exception/outofspaceexception.zep.c
	zend/cache/exception/runtimeexception.zep.c
	zend/cache/exception/unexpectedvalueexception.zep.c
	zend/cache/exception/unsupportedmethodcallexception.zep.c
	zend/cache/storage/flushableinterface.zep.c
	zend/cache/storage/iterableinterface.zep.c
	zend/cache/storage/taggableinterface.zep.c
	zend/cache/storage/totalspacecapableinterface.zep.c
	zend/captcha/exception/domainexception.zep.c
	zend/captcha/exception/exceptioninterface.zep.c
	zend/captcha/exception/extensionnotloadedexception.zep.c
	zend/captcha/exception/imagenotloadableexception.zep.c
	zend/captcha/exception/invalidargumentexception.zep.c
	zend/captcha/exception/nofontprovidedexception.zep.c
	zend/captcha/exception/runtimeexception.zep.c
	zend/code/exception/badmethodcallexception.zep.c
	zend/code/exception/exceptioninterface.zep.c
	zend/code/exception/invalidargumentexception.zep.c
	zend/code/exception/runtimeexception.zep.c
	zend/code/generator/exception/exceptioninterface.zep.c
	zend/code/generator/exception/invalidargumentexception.zep.c
	zend/code/generator/exception/runtimeexception.zep.c
	zend/code/reflection/exception/badmethodcallexception.zep.c
	zend/code/reflection/exception/exceptioninterface.zep.c
	zend/code/reflection/exception/invalidargumentexception.zep.c
	zend/code/reflection/exception/runtimeexception.zep.c
	zend/config/exception/exceptioninterface.zep.c
	zend/config/exception/invalidargumentexception.zep.c
	zend/config/exception/runtimeexception.zep.c
	zend/config/reader/readerinterface.zep.c
	zend/console/exception/badmethodcallexception.zep.c
	zend/console/exception/exceptioninterface.zep.c
	zend/console/exception/invalidargumentexception.zep.c
	zend/console/exception/runtimeexception.zep.c
	zend/crypt/exception/exceptioninterface.zep.c
	zend/crypt/exception/invalidargumentexception.zep.c
	zend/crypt/exception/runtimeexception.zep.c
	zend/crypt/key/derivation/exception/exceptioninterface.zep.c
	zend/crypt/key/derivation/exception/invalidargumentexception.zep.c
	zend/crypt/key/derivation/exception/runtimeexception.zep.c
	zend/crypt/password/exception/exceptioninterface.zep.c
	zend/crypt/password/exception/invalidargumentexception.zep.c
	zend/crypt/password/exception/runtimeexception.zep.c
	zend/crypt/publickey/rsa/exception/exceptioninterface.zep.c
	zend/crypt/publickey/rsa/exception/invalidargumentexception.zep.c
	zend/crypt/publickey/rsa/exception/runtimeexception.zep.c
	zend/crypt/symmetric/exception/exceptioninterface.zep.c
	zend/crypt/symmetric/exception/invalidargumentexception.zep.c
	zend/crypt/symmetric/exception/runtimeexception.zep.c
	zend/db/adapter/driver/sqlsrv/exception/errorexception.zep.c
	zend/db/adapter/driver/sqlsrv/exception/exceptioninterface.zep.c
	zend/db/adapter/exception/errorexception.zep.c
	zend/db/adapter/exception/exceptioninterface.zep.c
	zend/db/adapter/exception/invalidargumentexception.zep.c
	zend/db/adapter/exception/invalidconnectionparametersexception.zep.c
	zend/db/adapter/exception/invalidqueryexception.zep.c
	zend/db/adapter/exception/runtimeexception.zep.c
	zend/db/adapter/exception/unexpectedvalueexception.zep.c
	zend/db/exception/errorexception.zep.c
	zend/db/exception/exceptioninterface.zep.c
	zend/db/exception/invalidargumentexception.zep.c
	zend/db/exception/runtimeexception.zep.c
	zend/db/exception/unexpectedvalueexception.zep.c
	zend/db/resultset/exception/exceptioninterface.zep.c
	zend/db/resultset/exception/invalidargumentexception.zep.c
	zend/db/resultset/exception/runtimeexception.zep.c
	zend/db/rowgateway/exception/exceptioninterface.zep.c
	zend/db/rowgateway/exception/invalidargumentexception.zep.c
	zend/db/rowgateway/exception/runtimeexception.zep.c
	zend/db/sql/exception/exceptioninterface.zep.c
	zend/db/sql/exception/invalidargumentexception.zep.c
	zend/db/sql/exception/runtimeexception.zep.c
	zend/db/tablegateway/exception/exceptioninterface.zep.c
	zend/db/tablegateway/exception/invalidargumentexception.zep.c
	zend/db/tablegateway/exception/runtimeexception.zep.c
	zend/di/exception/circulardependencyexception.zep.c
	zend/di/exception/classnotfoundexception.zep.c
	zend/di/exception/exceptioninterface.zep.c
	zend/di/exception/invalidargumentexception.zep.c
	zend/di/exception/invalidcallbackexception.zep.c
	zend/di/exception/invalidparamnameexception.zep.c
	zend/di/exception/invalidpositionexception.zep.c
	zend/di/exception/missingpropertyexception.zep.c
	zend/di/exception/runtimeexception.zep.c
	zend/di/exception/undefinedreferenceexception.zep.c
	zend/dom/exception/badmethodcallexception.zep.c
	zend/dom/exception/exceptioninterface.zep.c
	zend/dom/exception/runtimeexception.zep.c
	zend/escaper/exception/exceptioninterface.zep.c
	zend/escaper/exception/invalidargumentexception.zep.c
	zend/escaper/exception/runtimeexception.zep.c
	zend/eventmanager/exception/domainexception.zep.c
	zend/eventmanager/exception/exceptioninterface.zep.c
	zend/eventmanager/exception/invalidargumentexception.zep.c
	zend/eventmanager/exception/invalidcallbackexception.zep.c
	zend/feed/exception/badmethodcallexception.zep.c
	zend/feed/exception/exceptioninterface.zep.c
	zend/feed/exception/invalidargumentexception.zep.c
	zend/feed/exception/runtimeexception.zep.c
	zend/feed/pubsubhubbub/exception/exceptioninterface.zep.c
	zend/feed/pubsubhubbub/exception/invalidargumentexception.zep.c
	zend/feed/pubsubhubbub/exception/runtimeexception.zep.c
	zend/feed/reader/exception/badmethodcallexception.zep.c
	zend/feed/reader/exception/exceptioninterface.zep.c
	zend/feed/reader/exception/invalidargumentexception.zep.c
	zend/feed/reader/exception/runtimeexception.zep.c
	zend/feed/writer/exception/badmethodcallexception.zep.c
	zend/feed/writer/exception/exceptioninterface.zep.c
	zend/feed/writer/exception/invalidargumentexception.zep.c
	zend/feed/writer/exception/runtimeexception.zep.c
	zend/file/exception/badmethodcallexception.zep.c
	zend/file/exception/exceptioninterface.zep.c
	zend/file/exception/invalidargumentexception.zep.c
	zend/file/exception/runtimeexception.zep.c
	zend/file/transfer/exception/badmethodcallexception.zep.c
	zend/file/transfer/exception/exceptioninterface.zep.c
	zend/file/transfer/exception/invalidargumentexception.zep.c
	zend/file/transfer/exception/phpenvironmentexception.zep.c
	zend/file/transfer/exception/runtimeexception.zep.c
	zend/filter/compress/compressionalgorithminterface.zep.c
	zend/filter/encrypt/encryptionalgorithminterface.zep.c
	zend/filter/exception/badmethodcallexception.zep.c
	zend/filter/exception/domainexception.zep.c
	zend/filter/exception/exceptioninterface.zep.c
	zend/filter/exception/extensionnotloadedexception.zep.c
	zend/filter/exception/invalidargumentexception.zep.c
	zend/filter/exception/runtimeexception.zep.c
	zend/filter/filterinterface.zep.c
	zend/form/exception/badmethodcallexception.zep.c
	zend/form/exception/domainexception.zep.c
	zend/form/exception/exceptioninterface.zep.c
	zend/form/exception/extensionnotloadedexception.zep.c
	zend/form/exception/invalidargumentexception.zep.c
	zend/form/exception/invalidelementexception.zep.c
	zend/form/exception/unexpectedvalueexception.zep.c
	zend/http/client/adapter/exception/exceptioninterface.zep.c
	zend/http/client/adapter/exception/initializationexception.zep.c
	zend/http/client/adapter/exception/invalidargumentexception.zep.c
	zend/http/client/adapter/exception/outofrangeexception.zep.c
	zend/http/client/adapter/exception/runtimeexception.zep.c
	zend/http/client/adapter/exception/timeoutexception.zep.c
	zend/http/client/exception/exceptioninterface.zep.c
	zend/http/client/exception/invalidargumentexception.zep.c
	zend/http/client/exception/outofrangeexception.zep.c
	zend/http/client/exception/runtimeexception.zep.c
	zend/http/exception/exceptioninterface.zep.c
	zend/http/exception/invalidargumentexception.zep.c
	zend/http/exception/outofrangeexception.zep.c
	zend/http/exception/runtimeexception.zep.c
	zend/http/header/exception/domainexception.zep.c
	zend/http/header/exception/exceptioninterface.zep.c
	zend/http/header/exception/invalidargumentexception.zep.c
	zend/http/header/exception/runtimeexception.zep.c
	zend/i18n/exception/exceptioninterface.zep.c
	zend/i18n/exception/extensionnotloadedexception.zep.c
	zend/i18n/exception/invalidargumentexception.zep.c
	zend/i18n/exception/outofboundsexception.zep.c
	zend/i18n/exception/parseexception.zep.c
	zend/i18n/exception/rangeexception.zep.c
	zend/i18n/exception/runtimeexception.zep.c
	zend/inputfilter/exception/exceptioninterface.zep.c
	zend/inputfilter/exception/invalidargumentexception.zep.c
	zend/inputfilter/exception/runtimeexception.zep.c
	zend/json/exception/badmethodcallexception.zep.c
	zend/json/exception/exceptioninterface.zep.c
	zend/json/exception/invalidargumentexception.zep.c
	zend/json/exception/recursionexception.zep.c
	zend/json/exception/runtimeexception.zep.c
	zend/json/server/exception/errorexception.zep.c
	zend/json/server/exception/exceptioninterface.zep.c
	zend/json/server/exception/httpexception.zep.c
	zend/json/server/exception/invalidargumentexception.zep.c
	zend/json/server/exception/runtimeexception.zep.c
	zend/ldap/converter/exception/converterexception.zep.c
	zend/ldap/converter/exception/exceptioninterface.zep.c
	zend/ldap/converter/exception/invalidargumentexception.zep.c
	zend/ldap/converter/exception/unexpectedvalueexception.zep.c
	zend/ldap/exception/badmethodcallexception.zep.c
	zend/ldap/exception/exceptioninterface.zep.c
	zend/ldap/exception/invalidargumentexception.zep.c
	zend/ldap/exception/ldapexception.zep.c
	zend/ldap/filter/exception/exceptioninterface.zep.c
	zend/ldap/filter/exception/filterexception.zep.c
	zend/loader/autoloaderfactory.zep.c
	zend/loader/classmapautoloader.zep.c
	zend/loader/exception/badmethodcallexception.zep.c
	zend/loader/exception/domainexception.zep.c
	zend/loader/exception/exceptioninterface.zep.c
	zend/loader/exception/invalidargumentexception.zep.c
	zend/loader/exception/invalidpathexception.zep.c
	zend/loader/exception/missingresourcenamespaceexception.zep.c
	zend/loader/exception/pluginloaderexception.zep.c
	zend/loader/exception/runtimeexception.zep.c
	zend/loader/exception/securityexception.zep.c
	zend/loader/moduleautoloader.zep.c
	zend/loader/pluginclassloader.zep.c
	zend/loader/pluginclasslocator.zep.c
	zend/loader/shortnamelocator.zep.c
	zend/loader/splautoloader.zep.c
	zend/loader/standardautoloader.zep.c
	zend/log/exception/exceptioninterface.zep.c
	zend/log/exception/invalidargumentexception.zep.c
	zend/log/exception/runtimeexception.zep.c
	zend/log/filter/filterinterface.zep.c
	zend/log/formatter/formatterinterface.zep.c
	zend/log/loggerinterface.zep.c
	zend/log/processor/processorinterface.zep.c
	zend/log/writer/chromephp/chromephpinterface.zep.c
	zend/log/writer/writerinterface.zep.c
	zend/mail/exception/badmethodcallexception.zep.c
	zend/mail/exception/domainexception.zep.c
	zend/mail/exception/exceptioninterface.zep.c
	zend/mail/exception/invalidargumentexception.zep.c
	zend/mail/exception/outofboundsexception.zep.c
	zend/mail/exception/runtimeexception.zep.c
	zend/mail/header/exception/badmethodcallexception.zep.c
	zend/mail/header/exception/exceptioninterface.zep.c
	zend/mail/header/exception/invalidargumentexception.zep.c
	zend/mail/header/exception/runtimeexception.zep.c
	zend/mail/protocol/exception/exceptioninterface.zep.c
	zend/mail/protocol/exception/invalidargumentexception.zep.c
	zend/mail/protocol/exception/runtimeexception.zep.c
	zend/mail/storage/exception/exceptioninterface.zep.c
	zend/mail/storage/exception/invalidargumentexception.zep.c
	zend/mail/storage/exception/outofboundsexception.zep.c
	zend/mail/storage/exception/runtimeexception.zep.c
	zend/mail/storage/part/exception/exceptioninterface.zep.c
	zend/mail/storage/part/exception/invalidargumentexception.zep.c
	zend/mail/storage/part/exception/runtimeexception.zep.c
	zend/mail/transport/exception/domainexception.zep.c
	zend/mail/transport/exception/exceptioninterface.zep.c
	zend/mail/transport/exception/invalidargumentexception.zep.c
	zend/mail/transport/exception/runtimeexception.zep.c
	zend/math/biginteger/exception/divisionbyzeroexception.zep.c
	zend/math/biginteger/exception/exceptioninterface.zep.c
	zend/math/biginteger/exception/invalidargumentexception.zep.c
	zend/math/biginteger/exception/runtimeexception.zep.c
	zend/math/exception/domainexception.zep.c
	zend/math/exception/exceptioninterface.zep.c
	zend/math/exception/invalidargumentexception.zep.c
	zend/math/exception/runtimeexception.zep.c
	zend/memory/exception/exceptioninterface.zep.c
	zend/memory/exception/invalidargumentexception.zep.c
	zend/memory/exception/runtimeexception.zep.c
	zend/mime/exception/exceptioninterface.zep.c
	zend/mime/exception/runtimeexception.zep.c
	zend/modulemanager/exception/exceptioninterface.zep.c
	zend/modulemanager/exception/invalidargumentexception.zep.c
	zend/modulemanager/exception/missingdependencymoduleexception.zep.c
	zend/modulemanager/exception/runtimeexception.zep.c
	zend/modulemanager/listener/exception/exceptioninterface.zep.c
	zend/modulemanager/listener/exception/invalidargumentexception.zep.c
	zend/modulemanager/listener/exception/runtimeexception.zep.c
	zend/mvc/exception/badmethodcallexception.zep.c
	zend/mvc/exception/domainexception.zep.c
	zend/mvc/exception/exceptioninterface.zep.c
	zend/mvc/exception/invalidargumentexception.zep.c
	zend/mvc/exception/invalidcontrollerexception.zep.c
	zend/mvc/exception/invalidpluginexception.zep.c
	zend/mvc/exception/missinglocatorexception.zep.c
	zend/mvc/exception/runtimeexception.zep.c
	zend/mvc/router/exception/exceptioninterface.zep.c
	zend/mvc/router/exception/invalidargumentexception.zep.c
	zend/mvc/router/exception/runtimeexception.zep.c
	zend/navigation/exception/badmethodcallexception.zep.c
	zend/navigation/exception/domainexception.zep.c
	zend/navigation/exception/exceptioninterface.zep.c
	zend/navigation/exception/invalidargumentexception.zep.c
	zend/navigation/exception/outofboundsexception.zep.c
	zend/paginator/adapter/exception/exceptioninterface.zep.c
	zend/paginator/adapter/exception/invalidargumentexception.zep.c
	zend/paginator/adapter/exception/runtimeexception.zep.c
	zend/paginator/adapter/exception/unexpectedvalueexception.zep.c
	zend/paginator/exception/exceptioninterface.zep.c
	zend/paginator/exception/invalidargumentexception.zep.c
	zend/paginator/exception/runtimeexception.zep.c
	zend/paginator/exception/unexpectedvalueexception.zep.c
	zend/permissions/acl/assertion/exception/invalidassertionexception.zep.c
	zend/permissions/acl/exception/exceptioninterface.zep.c
	zend/permissions/acl/exception/invalidargumentexception.zep.c
	zend/permissions/acl/exception/runtimeexception.zep.c
	zend/permissions/rbac/exception/exceptioninterface.zep.c
	zend/permissions/rbac/exception/invalidargumentexception.zep.c
	zend/progressbar/adapter/exception/exceptioninterface.zep.c
	zend/progressbar/adapter/exception/invalidargumentexception.zep.c
	zend/progressbar/adapter/exception/runtimeexception.zep.c
	zend/progressbar/exception/exceptioninterface.zep.c
	zend/progressbar/exception/invalidargumentexception.zep.c
	zend/progressbar/exception/outofrangeexception.zep.c
	zend/progressbar/exception/phpenvironmentexception.zep.c
	zend/progressbar/exception/runtimeexception.zep.c
	zend/serializer/exception/exceptioninterface.zep.c
	zend/serializer/exception/extensionnotloadedexception.zep.c
	zend/serializer/exception/invalidargumentexception.zep.c
	zend/serializer/exception/runtimeexception.zep.c
	zend/server/exception/badmethodcallexception.zep.c
	zend/server/exception/exceptioninterface.zep.c
	zend/server/exception/invalidargumentexception.zep.c
	zend/server/exception/runtimeexception.zep.c
	zend/server/reflection/exception/badmethodcallexception.zep.c
	zend/server/reflection/exception/exceptioninterface.zep.c
	zend/server/reflection/exception/invalidargumentexception.zep.c
	zend/server/reflection/exception/runtimeexception.zep.c
	zend/servicemanager/exception/circulardependencyfoundexception.zep.c
	zend/servicemanager/exception/circularreferenceexception.zep.c
	zend/servicemanager/exception/exceptioninterface.zep.c
	zend/servicemanager/exception/invalidargumentexception.zep.c
	zend/servicemanager/exception/invalidservicenameexception.zep.c
	zend/servicemanager/exception/runtimeexception.zep.c
	zend/servicemanager/exception/servicenotcreatedexception.zep.c
	zend/servicemanager/exception/servicenotfoundexception.zep.c
	zend/session/exception/badmethodcallexception.zep.c
	zend/session/exception/exceptioninterface.zep.c
	zend/session/exception/invalidargumentexception.zep.c
	zend/session/exception/runtimeexception.zep.c
	zend/soap/exception/badmethodcallexception.zep.c
	zend/soap/exception/exceptioninterface.zep.c
	zend/soap/exception/extensionnotloadedexception.zep.c
	zend/soap/exception/invalidargumentexception.zep.c
	zend/soap/exception/runtimeexception.zep.c
	zend/soap/exception/unexpectedvalueexception.zep.c
	zend/stdlib/arrayserializableinterface.zep.c
	zend/stdlib/arraystack.zep.c
	zend/stdlib/dispatchableinterface.zep.c
	zend/stdlib/exception/badmethodcallexception.zep.c
	zend/stdlib/exception/domainexception.zep.c
	zend/stdlib/exception/exceptioninterface.zep.c
	zend/stdlib/exception/extensionnotloadedexception.zep.c
	zend/stdlib/exception/invalidargumentexception.zep.c
	zend/stdlib/exception/invalidcallbackexception.zep.c
	zend/stdlib/exception/logicexception.zep.c
	zend/stdlib/exception/runtimeexception.zep.c
	zend/stdlib/initializableinterface.zep.c
	zend/stdlib/messageinterface.zep.c
	zend/stdlib/parameterobjectinterface.zep.c
	zend/stdlib/parametersinterface.zep.c
	zend/stdlib/prioritylist.zep.c
	zend/stdlib/priorityqueue.zep.c
	zend/stdlib/requestinterface.zep.c
	zend/stdlib/responseinterface.zep.c
	zend/stdlib/splqueue.zep.c
	zend/stdlib/splstack.zep.c
	zend/tag/cloud/decorator/exception/exceptioninterface.zep.c
	zend/tag/cloud/decorator/exception/invalidargumentexception.zep.c
	zend/tag/exception/exceptioninterface.zep.c
	zend/tag/exception/invalidargumentexception.zep.c
	zend/tag/exception/invalidattributenameexception.zep.c
	zend/tag/exception/invalidelementnameexception.zep.c
	zend/tag/exception/outofboundsexception.zep.c
	zend/text/exception/exceptioninterface.zep.c
	zend/text/exception/invalidargumentexception.zep.c
	zend/text/exception/outofboundsexception.zep.c
	zend/text/exception/overflowexception.zep.c
	zend/text/exception/runtimeexception.zep.c
	zend/text/exception/unexpectedvalueexception.zep.c
	zend/text/figlet/exception/exceptioninterface.zep.c
	zend/text/figlet/exception/invalidargumentexception.zep.c
	zend/text/figlet/exception/runtimeexception.zep.c
	zend/text/figlet/exception/unexpectedvalueexception.zep.c
	zend/text/table/exception/exceptioninterface.zep.c
	zend/text/table/exception/invalidargumentexception.zep.c
	zend/text/table/exception/invaliddecoratorexception.zep.c
	zend/text/table/exception/outofboundsexception.zep.c
	zend/text/table/exception/overflowexception.zep.c
	zend/text/table/exception/unexpectedvalueexception.zep.c
	zend/uri/exception/exceptioninterface.zep.c
	zend/uri/exception/invalidargumentexception.zep.c
	zend/uri/exception/invaliduriexception.zep.c
	zend/uri/exception/invaliduripartexception.zep.c
	zend/validator/exception/badmethodcallexception.zep.c
	zend/validator/exception/exceptioninterface.zep.c
	zend/validator/exception/extensionnotloadedexception.zep.c
	zend/validator/exception/invalidargumentexception.zep.c
	zend/validator/exception/invalidmagicmimefileexception.zep.c
	zend/validator/exception/runtimeexception.zep.c
	zend/view/exception/badmethodcallexception.zep.c
	zend/view/exception/domainexception.zep.c
	zend/view/exception/exceptioninterface.zep.c
	zend/view/exception/invalidargumentexception.zep.c
	zend/view/exception/invalidhelperexception.zep.c
	zend/view/exception/runtimeexception.zep.c
	zend/view/exception/unexpectedvalueexception.zep.c
	zend/xmlrpc/client/exception/exceptioninterface.zep.c
	zend/xmlrpc/client/exception/faultexception.zep.c
	zend/xmlrpc/client/exception/httpexception.zep.c
	zend/xmlrpc/client/exception/introspectexception.zep.c
	zend/xmlrpc/client/exception/invalidargumentexception.zep.c
	zend/xmlrpc/client/exception/runtimeexception.zep.c
	zend/xmlrpc/exception/badmethodcallexception.zep.c
	zend/xmlrpc/exception/exceptioninterface.zep.c
	zend/xmlrpc/exception/invalidargumentexception.zep.c
	zend/xmlrpc/exception/runtimeexception.zep.c
	zend/xmlrpc/exception/valueexception.zep.c
	zend/xmlrpc/server/exception/badmethodcallexception.zep.c
	zend/xmlrpc/server/exception/exceptioninterface.zep.c
	zend/xmlrpc/server/exception/invalidargumentexception.zep.c
	zend/xmlrpc/server/exception/runtimeexception.zep.c "
	PHP_NEW_EXTENSION(zend, $zend_sources, $ext_shared,, )
	PHP_SUBST(ZEND_SHARED_LIBADD)

	old_CPPFLAGS=$CPPFLAGS
	CPPFLAGS="$CPPFLAGS $INCLUDES"

	AC_CHECK_DECL(
		[HAVE_BUNDLED_PCRE],
		[
			AC_CHECK_HEADERS(
				[ext/pcre/php_pcre.h],
				[
					PHP_ADD_EXTENSION_DEP([zend], [pcre])
					AC_DEFINE([ZEPHIR_USE_PHP_PCRE], [1], [Whether PHP pcre extension is present at compile time])
				],
				,
				[[#include "main/php.h"]]
			)
		],
		,
		[[#include "php_config.h"]]
	)

	AC_CHECK_DECL(
		[HAVE_JSON],
		[
			AC_CHECK_HEADERS(
				[ext/json/php_json.h],
				[
					PHP_ADD_EXTENSION_DEP([zend], [json])
					AC_DEFINE([ZEPHIR_USE_PHP_JSON], [1], [Whether PHP json extension is present at compile time])
				],
				,
				[[#include "main/php.h"]]
			)
		],
		,
		[[#include "php_config.h"]]
	)

	CPPFLAGS=$old_CPPFLAGS

	PHP_INSTALL_HEADERS([ext/zend], [php_ZEND.h])

fi
